# ==========================================
# 2D Integer Square Packing Solver (8 Subplots)
# Generated by Gemini
# ==========================================

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from dataclasses import dataclass
from matplotlib.axes import Axes
from time import perf_counter
from z3 import Solver, Int, Or, sat, ModelRef


@dataclass(frozen=True)
class PackingRun:
    status: str
    positions: list[tuple[int, int]] | None
    solver_time_seconds: float
    num_variables: int
    num_assertions: int
    num_boundary_constraints: int
    num_non_overlap_constraints: int
    total_square_area: int
    container_area: int


def solve_square_packing_with_stats(container_size: int, square_sizes: list[int]) -> PackingRun:
    solver = Solver()
    n = len(square_sizes)

    # Create x, y variables for the bottom-left corner of each square
    x_vars = [Int(f'x_{i}') for i in range(n)]
    y_vars = [Int(f'y_{i}') for i in range(n)]

    # 1. Boundary conditions
    for i in range(n):
        s = square_sizes[i]
        solver.add(x_vars[i] >= 0)
        solver.add(y_vars[i] >= 0)
        solver.add(x_vars[i] + s <= container_size)
        solver.add(y_vars[i] + s <= container_size)

    # 2. Non-overlapping conditions
    for i in range(n):
        for j in range(i + 1, n):
            left = x_vars[i] + square_sizes[i] <= x_vars[j]
            right = x_vars[j] + square_sizes[j] <= x_vars[i]
            bottom = y_vars[i] + square_sizes[i] <= y_vars[j]
            top = y_vars[j] + square_sizes[j] <= y_vars[i]

            solver.add(Or(left, right, bottom, top))

    # Execute the solver
    start_time = perf_counter()
    check_result = solver.check()
    solver_time_seconds = perf_counter() - start_time

    total_square_area = sum(s * s for s in square_sizes)
    container_area = container_size * container_size
    num_boundary_constraints = 4 * n
    num_non_overlap_constraints = n * (n - 1) // 2

    if check_result == sat:
        model: ModelRef = solver.model()
        positions = []
        for i in range(n):
            xi_val = model.eval(x_vars[i]).as_long()
            yi_val = model.eval(y_vars[i]).as_long()
            positions.append((xi_val, yi_val))
        status = "SAT"
    else:
        positions = None
        status = "UNSAT"

    return PackingRun(
        status=status,
        positions=positions,
        solver_time_seconds=solver_time_seconds,
        num_variables=2 * n,
        num_assertions=len(solver.assertions()),
        num_boundary_constraints=num_boundary_constraints,
        num_non_overlap_constraints=num_non_overlap_constraints,
        total_square_area=total_square_area,
        container_area=container_area,
    )


def solve_square_packing(container_size: int, square_sizes: list[int]) -> list[tuple[int, int]] | None:
    return solve_square_packing_with_stats(container_size, square_sizes).positions


def plot_square_packing_on_ax(ax: Axes, container_size: int, square_sizes: list[int], positions: list[tuple[int, int]] | None) -> None:
    # Draw the main container
    container = patches.Rectangle((0, 0), container_size, container_size, fill=False, edgecolor='black', linewidth=2)
    ax.add_patch(container)

    if positions is not None:
        # Draw each small square if a solution exists
        colors = plt.get_cmap('Set3')
        for i, (pos, s) in enumerate(zip(positions, square_sizes)):
            rect = patches.Rectangle(pos, s, s, fill=True, color=colors(i % 12), alpha=0.9, edgecolor='black', linewidth=1)
            ax.add_patch(rect)

            # Label the index and size
            center_x = pos[0] + s / 2
            center_y = pos[1] + s / 2
            ax.text(center_x, center_y, f"#{i}\n({s}x{s})", ha='center', va='center', fontsize=7)
        ax.set_title(f"L = {container_size} (Solved)", fontsize=10)
    else:
        # Show UNSAT message if no solution
        ax.text(container_size / 2, container_size / 2, "UNSAT\n(Too Small)", ha='center', va='center', color='red', fontsize=12, fontweight='bold')
        ax.set_title(f"L = {container_size} (Failed)", fontsize=10)

    # Set canvas limits and aspect ratio
    ax.set_xlim(-1, container_size + 1)
    ax.set_ylim(-1, container_size + 1)
    ax.set_aspect('equal')

    # Add grid lines (adjust frequency to avoid clutter on larger containers)
    step = max(1, container_size // 5)
    ax.set_xticks(range(0, container_size + 1, step))
    ax.set_yticks(range(0, container_size + 1, step))
    ax.grid(True, linestyle='--', alpha=0.5)


if __name__ == "__main__":
    from pathlib import Path

    # Example test
    Ls = [30, 25, 20, 15, 12, 11, 10, 9]
    # Sizes of the squares to be packed
    S = [5, 4, 3, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1]

    # Create a 2x4 grid for subplots
    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    fig.suptitle("Integer Square Packing with Z3", fontsize=14)

    # Flatten the 2D axes array to easily iterate over it
    axes_flat = axes.flatten()
    runs = []

    for idx, L in enumerate(Ls):
        print(f"[{idx+1}/8] Trying to pack {len(S)} squares into a {L}x{L} container...")
        run = solve_square_packing_with_stats(L, S)
        runs.append((L, run))

        if run.positions:
            print(f" -> Solution found for L = {L}.")
        else:
            print(f" -> No solution (Unsat) for L = {L}.")
        print(
            " "
            f"status={run.status}, "
            f"time={run.solver_time_seconds:.4f}s, "
            f"vars={run.num_variables}, "
            f"assertions={run.num_assertions}, "
            f"area={run.total_square_area}/{run.container_area}"
        )

        # Draw on the corresponding subplot
        current_ax = axes_flat[idx]
        plot_square_packing_on_ax(current_ax, L, S, run.positions)

    print("\nExperiment summary:")
    print("L,#Squares,TotalArea,ContainerArea,Status,SolverTimeSeconds,Variables,Assertions,BoundaryConstraints,NonOverlapConstraints")
    for L, run in runs:
        print(
            f"{L},{len(S)},{run.total_square_area},{run.container_area},"
            f"{run.status},{run.solver_time_seconds:.6f},{run.num_variables},"
            f"{run.num_assertions},{run.num_boundary_constraints},"
            f"{run.num_non_overlap_constraints}"
        )

    # Adjust layout to prevent overlap and show the plot
    plt.tight_layout()

    # --- Added code for saving the image starts here ---
    # Create the 'imgs' folder (it won't cause an error if it already exists)
    output_dir = Path("imgs")
    output_dir.mkdir(exist_ok=True)

    # Set the path and save the image (dpi=300 makes it look clearer on GitHub)
    save_path = output_dir / "example.png"
    plt.savefig(save_path, dpi=300)
    print(f"Image saved to: {save_path}")
    # --- Added code for saving the image ends here ---

    # Keep this line if you still want to see the pop-up window in VS Code; delete it if you only want to save the file
    plt.show()
